language: C

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - TEST_DIR=BNF  

# before_install:
  # gcc -4.8
  # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  # - sudo apt-get update -q
  # - sudo apt-get install gcc-4.8 -y

script: 
  - make
  - make test
